# numpy

In [5]:
import numpy as np
test_array=np.array([1,4,5,8],float)

* numpy는 **"하나의 데이터 타입"**만 배열에 넣을 수 있음.
* 리스트와 가장 큰 차이점 : dynamic typing not supported
* C의 Array 사용해 배열 생성
* numpy는 리스트와 달리 주소가 아니라 값이 메모리에 올라가고, 값들이 차례대로 값이 들어가있다. 따라서, 연산에 효율적. 메모리 접근성도 좋다. 

In [6]:
test_array=np.array(["1","4",5.0,7],float)
test_array

array([1., 4., 5., 7.])

In [5]:
type(test_array[0])

numpy.float64

In [7]:
a=[1,2,3,4,5]
b=[5,4,3,2,1]
a[0] is b[-1] #메모리 주소가 같다.

True

In [8]:
a=np.array(a)
b=np.array(b)
a[0] is b[-1] #메모리 비교시 false 

False

In [9]:
np.array([[1,2,3],[4,"5","6"]],dtype=np.float32).nbytes # 메모리 크기 반환

24

## array의 rank에 따라 불리는 이름이 있음
0 : scalar (ex) 7

1 : vector (ex) [10,10]

2 : matrix (ex) [[10,10],[15,15]]

3 : 3-tensor (ex) [[[1,5,9],[2,6,10]]]

n : n-tensor

In [11]:
tensor=[
    [[1,2,3,4],[1,2,3,4],[1,2,3,4]],
    [[1,2,3,4],[1,2,3,4],[1,2,3,4]],
    [[1,2,3,4],[1,2,3,4],[1,2,3,4]],
    [[1,2,3,4],[1,2,3,4],[1,2,3,4]],
]

In [12]:
np.array(tensor,int).ndim

3

In [14]:
np.array(tensor,int).size

48

In [16]:
np.array(tensor,dtype=float).nbytes

384

In [17]:
# Hadling shpae

In [ ]:
* reshape : Array의 shape 크기를 변경함. element 개수는 동일

In [18]:
test_matrix=[[1,2,3,4],[1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [19]:
np.array(test_matrix).reshape(8,)

array([1, 2, 3, 4, 1, 2, 5, 8])

In [21]:
np.array(test_matrix).reshape(-1,2).shape # -1 : size 기반으로 row개수 선정

(4, 2)

In [22]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [ ]:
# flat or flatten : 다차원 array를 1차원 array로 변환

In [23]:
test_matrix=[[
    [1, 2],[3, 4]],
    [[1, 2],[5, 8]]
]

In [24]:
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8])

# indexing & slicing
* list와 달리 이차원 배열에서 [0,0] 표기법을 제공함
* 매트릭스의 경우 앞은 row, 뒤는 colum

In [32]:
test_matrix=np.array([[1,2,3],[4,5,6]],int)

In [33]:
test_matrix[0][0]

1

In [34]:
test_matrix[0,0]

1

In [36]:
test_matrix[0,0]=10

In [37]:
test_matrix

array([[10,  2,  3],
       [ 4,  5,  6]])

# slicing
* 리스트와 달리 행과 열 부분을 나눠서 슬라이싱이 가능함.
* 매트릭스의 부분 집합을 추출할 때 유용

In [40]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]],int)
a[:,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [41]:
a[1,1:3]

array([7, 8])

In [42]:
a[1:3] # 1 row~ 2row

array([[ 6,  7,  8,  9, 10]])

In [43]:
test_array=np.array([[1,2,5,8],[1,2,5,8],[1,2,5,8],[1,2,5,8]],int)

In [44]:
test_array

array([[1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8]])

In [45]:
test_array[1:2,2:]

array([[5, 8]])

In [48]:
test_array=np.array([[1,2,5,8],[1,2,5,8]],int)

In [49]:
test_array[1]

array([1, 2, 5, 8])

In [50]:
test_array[1:3]

array([[1, 2, 5, 8]])

In [52]:
a=np.arange(100).reshape(10,10) 
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [53]:
a[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [54]:
a[:,::2]

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98]])

## creation function

In [57]:
# 1. arange : array 범위 지정해 값의 리스트를 생성하는 명령어
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [59]:
np.arange(0,5,0.5) # floating point로 step 가능

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [61]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [78]:
# 2. ones, zeros and empty
np.zeros(shape=(10,),dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [63]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [66]:
# empty의 경우 메모리 잡기는 하지만 memory initialization이 되지 않음
np.empty(shape=(20,),dtype=np.int8) # shape만 주어지고 비어있는 ndarray생성

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5, 0, 0, 0],
      dtype=int8)

In [68]:
# 3. something_like - 기존 ndarray의 shape 크기 만큼 1,0또는 empty array 반환

In [72]:
test_matrix = np.arange(30).reshape(5,6)
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [ ]:
## eye,identity& digonal

In [79]:
# 4. identity : 단위 행렬 생성
np.identity(n=3,dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [80]:
# 5. eye : 대각선이 1인 행렬. k값의 시작 인덱스 변경 가능
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [81]:
np.eye(3,5,k=2) # k :시작하는 열

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# 6. diag : 대각 행렬의 값 추출

In [82]:
matrix=np.arange(9).reshape(3,3)
np.diag(matrix)

array([0, 4, 8])

In [83]:
np.diag(matrix,k=1) # k : start idx

array([1, 5])

## numpy.random
* random sampling - 데이터 분포에 따른 sampling으로 array 생성

In [85]:
np.random.uniform(0,1,10).reshape(2,5) # 균등 분포

array([[0.07092477, 0.30709293, 0.84334154, 0.52496792, 0.29790778],
       [0.54515178, 0.38768373, 0.02961297, 0.8149337 , 0.79797335]])

In [87]:
np.random.uniform(0,1,10).reshape(2,5) # 정규 분포

array([[0.2239035 , 0.5924722 , 0.93070474, 0.83801373, 0.34631762],
       [0.0327903 , 0.49863433, 0.86493194, 0.45638792, 0.25048327]])

In [9]:
np.random.exponential(scale=2, size=100)

array([ 2.4934302 ,  0.56808472,  2.06863389,  2.58003405,  6.96071396,
        1.74303664, 10.10261725,  4.47195958,  1.28478421,  3.19832974,
        0.72523414,  0.4677355 ,  2.05327526,  2.55497426,  4.14377817,
        0.93137921,  0.13007317,  1.05389246,  3.68026567,  0.42409419,
        2.81887073,  0.47572501,  2.78750433,  1.81574579,  5.61169229,
        7.09789094,  7.34892552,  1.04627942,  3.64684433,  0.80355756,
        0.65877637,  0.46406929,  1.84848691,  3.23362474,  0.47225013,
        6.80221537,  5.81675795,  5.61574225,  7.87616828,  4.37015117,
        1.37507784,  0.46252823,  1.13267391,  2.41867268,  0.68278228,
        0.3024826 ,  1.48796792,  5.56366733,  8.15748387,  0.39934592,
        0.17112509,  0.02450228,  1.24744173,  5.00132175,  2.5964141 ,
        4.29828828,  3.21518634,  0.59730548,  0.53894048,  1.00649252,
        4.38184497,  1.71787021, 14.07425892,  0.11414647,  2.32689356,
        0.0360409 ,  1.70170184,  1.57176807,  0.29186086,  3.61

# axis

In [12]:
test_array=np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
test_array.sum(axis=1), test_array.sum(axis=0)

(array([10, 26, 42]), array([15, 18, 21, 24]))

In [14]:
third_order_tensor=np.array([test_array,test_array,test_array])

In [15]:
third_order_tensor.shape

(3, 3, 4)

In [17]:
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [16]:
third_order_tensor.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [18]:
third_order_tensor.sum(axis=0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [19]:
third_order_tensor.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [20]:
# Comcatenate - numpy array를 붙이는 함수

In [30]:
a=np.array([1,2,3])
b=np.array([2,3,4])

In [31]:
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [37]:
a=np.array([[1,2,3]])
b=np.array([[2,3,4]])

In [38]:
np.concatenate((a,b),axis=0)

array([[1, 2, 3],
       [2, 3, 4]])

In [41]:
a=np.array([[1],[2],[3]])
b=np.array([[2],[3],[4]])

In [27]:
np.hstack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [42]:
np.concatenate((a,b),axis=1)

array([[1, 2],
       [2, 3],
       [3, 4]])

In [52]:
# + newaxis 
a=np.array([[1,2],[3,4]])
b=np.array([5,6]) # rank가 1인 벡터임. a와 더해지려면 dim+1해야

In [53]:
b=b[np.newaxis,:]
b

array([[5, 6]])

In [54]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

### array operations - array간 기본적인 사칙 연산 지원함
* element wise operations
    - array간 shape이 `같을 때` 일어나는 연산. 같은 위치에 있는 원소간 +,-,* 등
    - cf. braodcasting : shape이 다른 배열 간에 연산을 지원함 
* dot product 
    - 행렬 곱 떠올리기

In [57]:
# dot product
a=np.arange(1,7).reshape(2,3)
b=np.arange(7,13).reshape(3,2)

In [58]:
a.dot(b)

array([[ 58,  64],
       [139, 154]])

In [60]:
# transpose
a=np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [62]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [64]:
# broadcasting - scalar~vector 외에도 vector-matrix 간 연산도 지원
matrix=np.array([[1,2,3],[4,5,6]],float)
scalar=3
matrix+scalar

array([[4., 5., 6.],
       [7., 8., 9.]])

In [65]:
matrix*5

array([[ 5., 10., 15.],
       [20., 25., 30.]])

In [66]:
matrix=np.arange(1,13).reshape(4,3)
vector=np.arange(10,40,10)
matrix+vector

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

In [8]:
# timeit으로 numpy performance 체크하기
def scalar_vector_product(scalar,vector):
    res=[]
    for val in vector:
        res.append(scalar*val)
    return res

iternation_max=100000000
vector=list(range(iternation_max))
scalar=2

In [ ]:
%timeit scalar_vector_product(scalar,vector)
%timeit [scalar*value for value in range(iternation_max)]

In [ ]:
%timeit np.arange(iternation_max)*scalar

속도는 
* for loop < list compre < numpy 
* 100,000,000번의 루프가 돌 때 약 4배 이상의 성능 차이 보임
* numpy C로 구현되어 있어 성능 확보하는 대신 파이썬의 동적 타이핑 포기함
* concentenate처럼 계산이 아닌 할당에서는 연산 속도의 이점이 없음

In [2]:
# all & any
import numpy as np
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.any(a>5),np.any(a<0) # 하나라도 조건에 만족한다면

(True, False)

In [4]:
np.all(a>5) # 모두 조건에 만족한다면

False

In [5]:
# comparision operation : numpy는 배열의 크기가 동일할 때, element간 비교 결과를 boolean type으로 반환

In [9]:
a=np.array([[1],[3],[1]],float)
b=np.array([[5],[2],[1]],float)

In [10]:
a>b

array([[False],
       [ True],
       [False]])

In [11]:
a==b

array([[False],
       [False],
       [ True]])

In [13]:
(a>b).any()

True

In [14]:
a=np.array([1,3,0],float)
np.logical_and(a>0,a<3) # [T,T,F]and[T,F,F] # or,not 연산도 가능

array([ True, False, False])

In [15]:
# np.where : 2가지 방식

In [16]:
np.where(a>0,3,2) # (condition,true,false)

array([3, 3, 2])

In [24]:
a=np.arange(10)
np.where(a>5) # 인덱스 반환

(array([6, 7, 8, 9], dtype=int64),)

In [25]:
np.where(a>5)[0]

array([6, 7, 8, 9], dtype=int64)

In [19]:
a=np.array([1,np.NaN,np.Inf],float)
np.isnan(a)

array([False,  True, False])

In [20]:
np.isfinite(a)

array([ True, False, False])

In [26]:
# argmax&argmin  & argsort
- array내 최대값, 최소값의 idx를 반환함
- axis 기반의 반환 가능

In [28]:
a=np.array([1,2,4,5,8,78,23,3])
np.argmax(a),np.argmin(a)

(5, 0)

In [29]:
a=np.array([[1,2,4,7],[9,88,6,56],[9,76,3,4]])
np.argmax(a,axis=1), np.argmin(a,axis=0)

(array([3, 1, 1], dtype=int64), array([0, 0, 2, 2], dtype=int64))

In [30]:
a=np.array([1,2,3,4,8,78,23,3])
a

array([ 1,  2,  3,  4,  8, 78, 23,  3])

In [31]:
a.argsort() # sort하되, 인덱스 보여줌

array([0, 1, 2, 7, 3, 4, 6, 5], dtype=int64)

In [32]:
# boolean idx
# 1. 특정 조건에 따른 값을 배열로 추출
# 2. comparison operation 함수들도 모두 사용 가능

In [33]:
arr=np.array([1,4,0,2,3,8,9,7],float)
arr>3

array([False,  True, False, False, False,  True,  True,  True])

In [34]:
arr[arr>3]

array([4., 8., 9., 7.])

In [35]:
condition=arr<3
arr[condition]

array([1., 0., 2.])

In [ ]:
# fancy idx
# numpy는 array를 index value로 사용해서 값 추출

# boolean idx 와의 차이
# 1. idx가 boolean이냐 integer list냐의 차이
# 2. boolean과 달리 배열 크기 서로 달라도 됨, 다만 인덱스 범위는 맞게 설정해야

In [36]:
a=np.array([2,4,6,8],float)
b=np.array([0,0,1,3,2,1],int) # 반드시 integer로 선언
a[b] # bracket index, b배열의 값을 idx로 하여 a값들 추출함

array([2., 2., 4., 8., 6., 4.])

In [37]:
a.take(b) # bracket index와 같은 효과

array([2., 2., 4., 8., 6., 4.])

In [39]:
a=np.array([[1,4],[9,6]],float)
b=np.array([0,0,1,1,0],int)
c=np.array([0,1,1,1,1],int)
a[b,c] # b를 row idx, c를 col idx로 변환해 표시 - arr[0][0],arr[0][1] 등이 표현됨

array([1., 4., 6., 6., 4.])

In [41]:
a=np.array([[1,4],[9,16]],float)
a[b]

array([[ 1.,  4.],
       [ 1.,  4.],
       [ 9., 16.],
       [ 9., 16.],
       [ 1.,  4.]])

In [42]:
# numpy data i/o

In [ ]:
# loadtxt and save txt
a=np.loadtxt('./test.txt')
a[:10]

In [ ]:
a_int=a.astype(int)
a_int[:3]

In [ ]:
np.savetxt('int_data.csv',a_int,fmt="%.2e",delimiter=',')

In [ ]:
# numpy object - npy
np.save("npy_test_object",arr=a_int)
a_test=np.load(file="npy_test.npy")
npy_array=np.load(file="npy_test.npy")